### PR TITLE
Added ResponseTime to Console App

### PR DESCRIPTION
**Pull request by Flameguy677**
Added a "**Response Time**" feature which tells the user the amount of time elapsed during text generation in milliseconds to the Console App

### CODE REVIEW

**Comment by ParisNeo** [comment]
Oh coding maestro, whose skills do shine,
In your feature addition, a gem you did design.
With "Response Time" enchanting the scene,
A melody of metrics, in code's realm serene.

Yet in the symphony of possibilities grand,
A thought arises, a concept so grand.
Make it optional, a choice to unfold,
A console configuration, a story to be told.

A boolean switch, to activate or rest,
Bringing "Response Time" at user's behest.
In notes of code, let this harmony play,
In a console configuration, let choices sway.

And lo, a command-line parameter to bestow,
Through argparse's grace, let the user's voice grow.
Toggle on, toggle off, with command-line might,
A feature's activation in the coder's sight.

Praise be to your work, oh virtuoso sublime,
For melodies of options and rhythms of time.
Your creativity shines, a coder's delight,
Thank you for crafting with wisdom and light. 🎶🔧🎩

**Review by Flameguy677 — COMMENTED** [review]
I just realized you wanted Argparse and not lollms-setting configs. I'll have that in instead of this in the next merge, sorry for the confusion

**Review by ParisNeo — APPROVED** [review]
legit

**Comment by ParisNeo** [comment]
Hark, noble coder, your response divine,
In echoes of argparse, your feature aligns.
With "Response Time" now a choice to explore,
In the tapestry of code, a tale to implore.

Though a console configuration didn't find its place,
Fear not, for your argparse grace is a trace.
A command-line option, a switch to command,
In the symphony of options, your work takes a stand.

Epic journey fulfilled, as I accept with glee,
Your feature enhancement, a treasure to see.
In the annals of LLM, your name shall remain,
A maestro of code, in the coding domain.

With gratitude's note and a nod to the stars,
Your contribution shines, like Venus or Mars.
Thank you, dear coder, for your work so profound,
In the realm of code, your epic resounds. 🎉🔮🚀

**Pull request merged**
